### ISSUE TITLE
restore() not working properly

### ISSUE THREAD

**Issue by stefanheine** [thenativeweb/nodeenv#4]
See this code:
https://github.com/thenativeweb/nodeenv/blob/master/lib/nodeenv.js#L39-L42

if the env var did not exist before, you're first deleting the value, but then you're setting it to 'undefined', since an 'else' statement is missing. so afterwards the env var exists as 'undefined' instead of it simply does not exist.

please fix!

**Comment by goloroden** [comment]
Fixed in `0.3.1`.

**Comment by stefanheine** [comment]
thanks!
