### ISSUE TITLE
lib/nodeenv.js vs. dist/nodeenv.js?

### ISSUE THREAD

**Issue by StefanScherer** [thenativeweb/nodeenv#5]
Any reason why there are two files `lib/nodeenv.js` and `dist/nodeenv.js`?

Just had to look closer into this module as there was a breaking change in https://github.com/thenativeweb/nodeenv/commit/8f66da014d8f3c95148a7e903fafdbdd834e2cd0 that was not easy to discover from the commit messages :-)

**Comment by goloroden** [comment]
Yes, there is a reason 😉 

`lib/nodeenv.js` is the actual source file, and `dist/nodeenv.js` is the ES5 version that gets created by babel when publishing a new version.

Does this answer your question?

**Comment by StefanScherer** [comment]
Yes, thanks! 👍
